package org.app.alice.modelo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ALERTA.
 */
public class Alerta {

    private Long id;
    private String descripcion;
    private Integer estatus;
    private Integer tipo_notificacion_id;
    private String mensaje;
    private String url;
    private String fecha;
    private Long entidad_id;
    private Long idUsuarioAlerta;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Alerta() {
    }

    public Alerta(Long id) {
        this.id = id;
    }

    public Alerta(Long id, String descripcion, Integer estatus, Integer tipo_notificacion_id, String mensaje, String url, String fecha, Long entidad_id, Long idUsuarioAlerta) {
        this.id = id;
        this.descripcion = descripcion;
        this.estatus = estatus;
        this.tipo_notificacion_id = tipo_notificacion_id;
        this.mensaje = mensaje;
        this.url = url;
        this.fecha = fecha;
        this.entidad_id = entidad_id;
        this.idUsuarioAlerta = idUsuarioAlerta;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getEstatus() {
        return estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    public Integer getTipo_notificacion_id() {
        return tipo_notificacion_id;
    }

    public void setTipo_notificacion_id(Integer tipo_notificacion_id) {
        this.tipo_notificacion_id = tipo_notificacion_id;
    }

    public String getMensaje() {
        return mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public Long getEntidad_id() {
        return entidad_id;
    }

    public void setEntidad_id(Long entidad_id) {
        this.entidad_id = entidad_id;
    }

    public Long getIdUsuarioAlerta() {
        return idUsuarioAlerta;
    }

    public void setIdUsuarioAlerta(Long idUsuarioAlerta) {
        this.idUsuarioAlerta = idUsuarioAlerta;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
