package org.app.alice.modelo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CITA.
 */
public class Cita {

    private Long id;
    private String fecha;
    private String descripcion;
    private String ubicacion;
    private Integer estatus;
    private Double precio;
    private String nombre;
    private String apellido;
    private Long idServicioCita;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Cita() {
    }

    public Cita(Long id) {
        this.id = id;
    }

    public Cita(Long id, String fecha, String descripcion, String ubicacion, Integer estatus, Double precio, String nombre, String apellido, Long idServicioCita) {
        this.id = id;
        this.fecha = fecha;
        this.descripcion = descripcion;
        this.ubicacion = ubicacion;
        this.estatus = estatus;
        this.precio = precio;
        this.nombre = nombre;
        this.apellido = apellido;
        this.idServicioCita = idServicioCita;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    public Integer getEstatus() {
        return estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    public Double getPrecio() {
        return precio;
    }

    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public Long getIdServicioCita() {
        return idServicioCita;
    }

    public void setIdServicioCita(Long idServicioCita) {
        this.idServicioCita = idServicioCita;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
