package org.app.alice.modelo;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.app.alice.modelo.Criterio;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CRITERIO.
*/
public class CriterioDao extends AbstractDao<Criterio, Long> {

    public static final String TABLENAME = "CRITERIO";

    /**
     * Properties of entity Criterio.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Codigo = new Property(1, Long.class, "codigo", false, "CODIGO");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Estatus = new Property(3, Integer.class, "estatus", false, "ESTATUS");
        public final static Property TipoCriterio = new Property(4, String.class, "tipoCriterio", false, "TIPO_CRITERIO");
        public final static Property Valor = new Property(5, Integer.class, "valor", false, "VALOR");
        public final static Property IdTipoServicioCriterio = new Property(6, Long.class, "idTipoServicioCriterio", false, "ID_TIPO_SERVICIO_CRITERIO");
    };

    private Query<Criterio> tipoServicio_CriterioQuery;

    public CriterioDao(DaoConfig config) {
        super(config);
    }
    
    public CriterioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CRITERIO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CODIGO' INTEGER," + // 1: codigo
                "'DESCRIPCION' TEXT," + // 2: descripcion
                "'ESTATUS' INTEGER," + // 3: estatus
                "'TIPO_CRITERIO' TEXT," + // 4: tipoCriterio
                "'VALOR' INTEGER," + // 5: valor
                "'ID_TIPO_SERVICIO_CRITERIO' INTEGER);"); // 6: idTipoServicioCriterio
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CRITERIO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Criterio entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long codigo = entity.getCodigo();
        if (codigo != null) {
            stmt.bindLong(2, codigo);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(3, descripcion);
        }
 
        Integer estatus = entity.getEstatus();
        if (estatus != null) {
            stmt.bindLong(4, estatus);
        }
 
        String tipoCriterio = entity.getTipoCriterio();
        if (tipoCriterio != null) {
            stmt.bindString(5, tipoCriterio);
        }
 
        Integer valor = entity.getValor();
        if (valor != null) {
            stmt.bindLong(6, valor);
        }
 
        Long idTipoServicioCriterio = entity.getIdTipoServicioCriterio();
        if (idTipoServicioCriterio != null) {
            stmt.bindLong(7, idTipoServicioCriterio);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Criterio readEntity(Cursor cursor, int offset) {
        Criterio entity = new Criterio( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // codigo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // descripcion
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // estatus
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // tipoCriterio
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // valor
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // idTipoServicioCriterio
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Criterio entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCodigo(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDescripcion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEstatus(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setTipoCriterio(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setValor(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setIdTipoServicioCriterio(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Criterio entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Criterio entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Criterio" to-many relationship of TipoServicio. */
    public List<Criterio> _queryTipoServicio_Criterio(Long idTipoServicioCriterio) {
        synchronized (this) {
            if (tipoServicio_CriterioQuery == null) {
                QueryBuilder<Criterio> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdTipoServicioCriterio.eq(null));
                tipoServicio_CriterioQuery = queryBuilder.build();
            }
        }
        Query<Criterio> query = tipoServicio_CriterioQuery.forCurrentThread();
        query.setParameter(0, idTipoServicioCriterio);
        return query.list();
    }

}
