package org.app.alice.modelo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CRITERIO.
 */
public class Criterio {

    private Long id;
    private Long codigo;
    private String descripcion;
    private Integer estatus;
    private String tipoCriterio;
    private Integer valor;
    private Long idTipoServicioCriterio;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Criterio() {
    }

    public Criterio(Long id) {
        this.id = id;
    }

    public Criterio(Long id, Long codigo, String descripcion, Integer estatus, String tipoCriterio, Integer valor, Long idTipoServicioCriterio) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.estatus = estatus;
        this.tipoCriterio = tipoCriterio;
        this.valor = valor;
        this.idTipoServicioCriterio = idTipoServicioCriterio;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCodigo() {
        return codigo;
    }

    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getEstatus() {
        return estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    public String getTipoCriterio() {
        return tipoCriterio;
    }

    public void setTipoCriterio(String tipoCriterio) {
        this.tipoCriterio = tipoCriterio;
    }

    public Integer getValor() {
        return valor;
    }

    public void setValor(Integer valor) {
        this.valor = valor;
    }

    public Long getIdTipoServicioCriterio() {
        return idTipoServicioCriterio;
    }

    public void setIdTipoServicioCriterio(Long idTipoServicioCriterio) {
        this.idTipoServicioCriterio = idTipoServicioCriterio;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
