package org.app.alice.modelo;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import org.app.alice.modelo.Evento;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table EVENTO.
*/
public class EventoDao extends AbstractDao<Evento, Long> {

    public static final String TABLENAME = "EVENTO";

    /**
     * Properties of entity Evento.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Codigo = new Property(1, Integer.class, "codigo", false, "CODIGO");
        public final static Property Titulo = new Property(2, String.class, "titulo", false, "TITULO");
        public final static Property Descripcion = new Property(3, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Contenido = new Property(4, String.class, "contenido", false, "CONTENIDO");
        public final static Property Estatus = new Property(5, Integer.class, "estatus", false, "ESTATUS");
        public final static Property TipoEvento = new Property(6, String.class, "tipoEvento", false, "TIPO_EVENTO");
        public final static Property TipoServicio = new Property(7, String.class, "tipoServicio", false, "TIPO_SERVICIO");
        public final static Property Foto = new Property(8, String.class, "foto", false, "FOTO");
        public final static Property Fecha = new Property(9, String.class, "fecha", false, "FECHA");
        public final static Property Lugar = new Property(10, String.class, "lugar", false, "LUGAR");
    };


    public EventoDao(DaoConfig config) {
        super(config);
    }
    
    public EventoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EVENTO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CODIGO' INTEGER," + // 1: codigo
                "'TITULO' TEXT," + // 2: titulo
                "'DESCRIPCION' TEXT," + // 3: descripcion
                "'CONTENIDO' TEXT," + // 4: contenido
                "'ESTATUS' INTEGER," + // 5: estatus
                "'TIPO_EVENTO' TEXT," + // 6: tipoEvento
                "'TIPO_SERVICIO' TEXT," + // 7: tipoServicio
                "'FOTO' TEXT," + // 8: foto
                "'FECHA' TEXT," + // 9: fecha
                "'LUGAR' TEXT);"); // 10: lugar
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EVENTO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Evento entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer codigo = entity.getCodigo();
        if (codigo != null) {
            stmt.bindLong(2, codigo);
        }
 
        String titulo = entity.getTitulo();
        if (titulo != null) {
            stmt.bindString(3, titulo);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(4, descripcion);
        }
 
        String contenido = entity.getContenido();
        if (contenido != null) {
            stmt.bindString(5, contenido);
        }
 
        Integer estatus = entity.getEstatus();
        if (estatus != null) {
            stmt.bindLong(6, estatus);
        }
 
        String tipoEvento = entity.getTipoEvento();
        if (tipoEvento != null) {
            stmt.bindString(7, tipoEvento);
        }
 
        String tipoServicio = entity.getTipoServicio();
        if (tipoServicio != null) {
            stmt.bindString(8, tipoServicio);
        }
 
        String foto = entity.getFoto();
        if (foto != null) {
            stmt.bindString(9, foto);
        }
 
        String fecha = entity.getFecha();
        if (fecha != null) {
            stmt.bindString(10, fecha);
        }
 
        String lugar = entity.getLugar();
        if (lugar != null) {
            stmt.bindString(11, lugar);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Evento readEntity(Cursor cursor, int offset) {
        Evento entity = new Evento( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // codigo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // titulo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // descripcion
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // contenido
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // estatus
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tipoEvento
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // tipoServicio
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // foto
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // fecha
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // lugar
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Evento entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCodigo(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setTitulo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDescripcion(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setContenido(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEstatus(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setTipoEvento(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTipoServicio(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFoto(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFecha(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setLugar(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Evento entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Evento entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
