package org.app.alice.modelo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table EVENTO.
 */
public class Evento {

    private Long id;
    private Integer codigo;
    private String titulo;
    private String descripcion;
    private String contenido;
    private Integer estatus;
    private String tipoEvento;
    private String tipoServicio;
    private String foto;
    private String fecha;
    private String lugar;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Evento() {
    }

    public Evento(Long id) {
        this.id = id;
    }

    public Evento(Long id, Integer codigo, String titulo, String descripcion, String contenido, Integer estatus, String tipoEvento, String tipoServicio, String foto, String fecha, String lugar) {
        this.id = id;
        this.codigo = codigo;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.contenido = contenido;
        this.estatus = estatus;
        this.tipoEvento = tipoEvento;
        this.tipoServicio = tipoServicio;
        this.foto = foto;
        this.fecha = fecha;
        this.lugar = lugar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getContenido() {
        return contenido;
    }

    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    public Integer getEstatus() {
        return estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    public String getTipoEvento() {
        return tipoEvento;
    }

    public void setTipoEvento(String tipoEvento) {
        this.tipoEvento = tipoEvento;
    }

    public String getTipoServicio() {
        return tipoServicio;
    }

    public void setTipoServicio(String tipoServicio) {
        this.tipoServicio = tipoServicio;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getLugar() {
        return lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
