package org.app.alice.modelo;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import org.app.alice.modelo.Servicio;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SERVICIO.
*/
public class ServicioDao extends AbstractDao<Servicio, Long> {

    public static final String TABLENAME = "SERVICIO";

    /**
     * Properties of entity Servicio.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Codigo = new Property(1, Integer.class, "codigo", false, "CODIGO");
        public final static Property Descripcion = new Property(2, String.class, "descripcion", false, "DESCRIPCION");
        public final static Property Estatus = new Property(3, Integer.class, "estatus", false, "ESTATUS");
        public final static Property Ubicacion = new Property(4, String.class, "ubicacion", false, "UBICACION");
        public final static Property Foto = new Property(5, String.class, "foto", false, "FOTO");
        public final static Property Precio = new Property(6, Double.class, "precio", false, "PRECIO");
        public final static Property Persona = new Property(7, String.class, "Persona", false, "PERSONA");
        public final static Property IdTipoServicio = new Property(8, Long.class, "idTipoServicio", false, "ID_TIPO_SERVICIO");
    };

    private DaoSession daoSession;

    private Query<Servicio> tipoServicio_ServicioQuery;

    public ServicioDao(DaoConfig config) {
        super(config);
    }
    
    public ServicioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'SERVICIO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CODIGO' INTEGER," + // 1: codigo
                "'DESCRIPCION' TEXT," + // 2: descripcion
                "'ESTATUS' INTEGER," + // 3: estatus
                "'UBICACION' TEXT," + // 4: ubicacion
                "'FOTO' TEXT," + // 5: foto
                "'PRECIO' REAL," + // 6: precio
                "'PERSONA' TEXT," + // 7: Persona
                "'ID_TIPO_SERVICIO' INTEGER);"); // 8: idTipoServicio
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SERVICIO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Servicio entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer codigo = entity.getCodigo();
        if (codigo != null) {
            stmt.bindLong(2, codigo);
        }
 
        String descripcion = entity.getDescripcion();
        if (descripcion != null) {
            stmt.bindString(3, descripcion);
        }
 
        Integer estatus = entity.getEstatus();
        if (estatus != null) {
            stmt.bindLong(4, estatus);
        }
 
        String ubicacion = entity.getUbicacion();
        if (ubicacion != null) {
            stmt.bindString(5, ubicacion);
        }
 
        String foto = entity.getFoto();
        if (foto != null) {
            stmt.bindString(6, foto);
        }
 
        Double precio = entity.getPrecio();
        if (precio != null) {
            stmt.bindDouble(7, precio);
        }
 
        String Persona = entity.getPersona();
        if (Persona != null) {
            stmt.bindString(8, Persona);
        }
 
        Long idTipoServicio = entity.getIdTipoServicio();
        if (idTipoServicio != null) {
            stmt.bindLong(9, idTipoServicio);
        }
    }

    @Override
    protected void attachEntity(Servicio entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Servicio readEntity(Cursor cursor, int offset) {
        Servicio entity = new Servicio( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // codigo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // descripcion
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // estatus
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ubicacion
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // foto
            cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6), // precio
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Persona
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // idTipoServicio
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Servicio entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCodigo(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setDescripcion(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEstatus(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setUbicacion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFoto(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPrecio(cursor.isNull(offset + 6) ? null : cursor.getDouble(offset + 6));
        entity.setPersona(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIdTipoServicio(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Servicio entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Servicio entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "Servicio" to-many relationship of TipoServicio. */
    public List<Servicio> _queryTipoServicio_Servicio(Long idTipoServicio) {
        synchronized (this) {
            if (tipoServicio_ServicioQuery == null) {
                QueryBuilder<Servicio> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.IdTipoServicio.eq(null));
                tipoServicio_ServicioQuery = queryBuilder.build();
            }
        }
        Query<Servicio> query = tipoServicio_ServicioQuery.forCurrentThread();
        query.setParameter(0, idTipoServicio);
        return query.list();
    }

}
