package org.app.alice.modelo;

import java.util.List;
import org.app.alice.modelo.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table SERVICIO.
 */
public class Servicio {

    private Long id;
    private Integer codigo;
    private String descripcion;
    private Integer estatus;
    private String ubicacion;
    private String foto;
    private Double precio;
    private String Persona;
    private Long idTipoServicio;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ServicioDao myDao;

    private List<Horario> Horario;
    private List<Cita> Cita;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Servicio() {
    }

    public Servicio(Long id) {
        this.id = id;
    }

    public Servicio(Long id, Integer codigo, String descripcion, Integer estatus, String ubicacion, String foto, Double precio, String Persona, Long idTipoServicio) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.estatus = estatus;
        this.ubicacion = ubicacion;
        this.foto = foto;
        this.precio = precio;
        this.Persona = Persona;
        this.idTipoServicio = idTipoServicio;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getServicioDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getEstatus() {
        return estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    public String getUbicacion() {
        return ubicacion;
    }

    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public Double getPrecio() {
        return precio;
    }

    public void setPrecio(Double precio) {
        this.precio = precio;
    }

    public String getPersona() {
        return Persona;
    }

    public void setPersona(String Persona) {
        this.Persona = Persona;
    }

    public Long getIdTipoServicio() {
        return idTipoServicio;
    }

    public void setIdTipoServicio(Long idTipoServicio) {
        this.idTipoServicio = idTipoServicio;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Horario> getHorario() {
        if (Horario == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            HorarioDao targetDao = daoSession.getHorarioDao();
            List<Horario> HorarioNew = targetDao._queryServicio_Horario(id);
            synchronized (this) {
                if(Horario == null) {
                    Horario = HorarioNew;
                }
            }
        }
        return Horario;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetHorario() {
        Horario = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Cita> getCita() {
        if (Cita == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CitaDao targetDao = daoSession.getCitaDao();
            List<Cita> CitaNew = targetDao._queryServicio_Cita(id);
            synchronized (this) {
                if(Cita == null) {
                    Cita = CitaNew;
                }
            }
        }
        return Cita;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetCita() {
        Cita = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
