package org.app.alice.modelo;

import java.util.List;
import org.app.alice.modelo.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TIPO_SERVICIO.
 */
public class TipoServicio {

    private Long id;
    private Integer codigo;
    private String descripcion;
    private String texto;
    private Integer estatus;
    private String foto;
    private Long idCategoriaServicio;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TipoServicioDao myDao;

    private List<Servicio> Servicio;
    private List<Criterio> Criterio;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TipoServicio() {
    }

    public TipoServicio(Long id) {
        this.id = id;
    }

    public TipoServicio(Long id, Integer codigo, String descripcion, String texto, Integer estatus, String foto, Long idCategoriaServicio) {
        this.id = id;
        this.codigo = codigo;
        this.descripcion = descripcion;
        this.texto = texto;
        this.estatus = estatus;
        this.foto = foto;
        this.idCategoriaServicio = idCategoriaServicio;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTipoServicioDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getTexto() {
        return texto;
    }

    public void setTexto(String texto) {
        this.texto = texto;
    }

    public Integer getEstatus() {
        return estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    public String getFoto() {
        return foto;
    }

    public void setFoto(String foto) {
        this.foto = foto;
    }

    public Long getIdCategoriaServicio() {
        return idCategoriaServicio;
    }

    public void setIdCategoriaServicio(Long idCategoriaServicio) {
        this.idCategoriaServicio = idCategoriaServicio;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Servicio> getServicio() {
        if (Servicio == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            ServicioDao targetDao = daoSession.getServicioDao();
            List<Servicio> ServicioNew = targetDao._queryTipoServicio_Servicio(id);
            synchronized (this) {
                if(Servicio == null) {
                    Servicio = ServicioNew;
                }
            }
        }
        return Servicio;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetServicio() {
        Servicio = null;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Criterio> getCriterio() {
        if (Criterio == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CriterioDao targetDao = daoSession.getCriterioDao();
            List<Criterio> CriterioNew = targetDao._queryTipoServicio_Criterio(id);
            synchronized (this) {
                if(Criterio == null) {
                    Criterio = CriterioNew;
                }
            }
        }
        return Criterio;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetCriterio() {
        Criterio = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
