package org.app.alice.modelo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TIPO_OPINIO.
 */
public class TipoOpinio {

    private Long id;
    private String descripcion;
    private Integer estatus;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TipoOpinio() {
    }

    public TipoOpinio(Long id) {
        this.id = id;
    }

    public TipoOpinio(Long id, String descripcion, Integer estatus) {
        this.id = id;
        this.descripcion = descripcion;
        this.estatus = estatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getEstatus() {
        return estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
