package org.app.alice.modelo;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TURNO.
 */
public class Turno {

    private Long id;
    private String inicio;
    private String fin;
    private Integer tipo;
    private Integer dia;
    private Integer estatus;
    private Long idHorarioTurno;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Turno() {
    }

    public Turno(Long id) {
        this.id = id;
    }

    public Turno(Long id, String inicio, String fin, Integer tipo, Integer dia, Integer estatus, Long idHorarioTurno) {
        this.id = id;
        this.inicio = inicio;
        this.fin = fin;
        this.tipo = tipo;
        this.dia = dia;
        this.estatus = estatus;
        this.idHorarioTurno = idHorarioTurno;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getInicio() {
        return inicio;
    }

    public void setInicio(String inicio) {
        this.inicio = inicio;
    }

    public String getFin() {
        return fin;
    }

    public void setFin(String fin) {
        this.fin = fin;
    }

    public Integer getTipo() {
        return tipo;
    }

    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    public Integer getDia() {
        return dia;
    }

    public void setDia(Integer dia) {
        this.dia = dia;
    }

    public Integer getEstatus() {
        return estatus;
    }

    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }

    public Long getIdHorarioTurno() {
        return idHorarioTurno;
    }

    public void setIdHorarioTurno(Long idHorarioTurno) {
        this.idHorarioTurno = idHorarioTurno;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
